version: "3.8"

services:
  mongo:
    image: mongo   
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
    - C:\Users\DIshant\Desktop\data:/data/db

  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/
    

    # docker compose -f "file name.yaml "  up -d 
    # docker compose -f "file name.yaml " down
    # the process of converting running application to a running docter container is called dockerization
    