version: "3.8"

services:
mongo:
    image: mongo   
    ports:
      - 27017:27017

    --name: mongo
    # --network: mongo-network # not needed for this example as yaml auto create a default network for you 

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty

mongo-express:
    image: mongo-express
    ports:
      - 8081:8081

    --name: mongo-express

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/
    

    # docker compose -f "file name.yaml "  up -d 
    # docker compose -f "file name.yaml " down